In [2]:
import pandas as pd

In [ ]:
# give information about data
# df = pd.read_csv("/content/demo.csv")

In [ ]:
# df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Series_reference  1200 non-null   object
 1   Period            1200 non-null   float64
 2   Data_value        1115 non-null   float64
 3   Suppressed        0 non-null      float64
 4   STATUS            1200 non-null   object
 5   UNITS             1200 non-null   object
 6   Magnitude         1200 non-null   int64
 7   Subject           1200 non-null   object
 8   Group             1200 non-null   object
 9   Series_title_1    1200 non-null   object
 10  Series_title_2    1200 non-null   object
 11  Series_title_3    1200 non-null   object
 12  Series_title_4    1200 non-null   object
 13  Series_title_5    0 non-null      float64
dtypes: float64(4), int64(1), object(9)
memory usage: 131.4+ KB

In [ ]:
# for run tsv files
# df = pd.read_csv("/content/sample-1.tsv" ,sep="\t")

In [ ]:
# df.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,2022,Create more with themes Go to Format >> Theme
0,NaN,JANUARY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FEBRUARY,...,MARCH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,S,M,T,W,T,F,S,NaN,S,...,S,M,T,W,T,F,S,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,...,NaN,NaN,1,2,3,4,5,NaN,NaN,NaN
3,NaN,2,3,4,5,6,7,8,NaN,6,...,6,7,8,9,10,11,12,NaN,NaN,NaN
4,NaN,9,10,11,12,13,14,15,NaN,13,...,13,14,15,16,17,18,19,NaN,NaN,NaN

In [ ]:
# for make first column as index
# df = pd.read_csv("/content/demo.csv", index_col='Series_reference')

# for make first column as header
# df = pd.read_csv("/content/demo.csv", index_col='Series_reference', header= 1)

In [ ]:
# df.head(3)

,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
Series_reference,,,,,,,,,,,,,
SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [ ]:
# for show specific columns
# df = pd.read_csv("/content/demo.csv", usecols=['Series_reference', 'Period', 'Data_value'])

In [ ]:
# df.head(5)

  Series_reference   Period  Data_value
0  SSSQ.SFMN1111CA  2004.06    1248.356
1  SSSQ.SFMN1111CA  2004.09    1220.571
2  SSSQ.SFMN1111CA  2004.12    1263.820
3  SSSQ.SFMN1111CA  2005.03    1146.156
4  SSSQ.SFMN1111CA  2005.06    1382.692

In [ ]:
# pandas series object
# df = pd.read_csv("/content/demo.csv", usecols=['Series_reference'], squeeze=True)

TypeError: read_csv() got an unexpected keyword argument 'squeeze'

In [ ]:
# for skip rows number 0 and 5
# df = pd.read_csv("/content/demo.csv", skiprows=[0,5])

In [ ]:
# df.head(5)

,SSSQ.SFMN1111CA,2004.06,1248.356,Unnamed: 3,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Services",Sales (operating income),Current prices,Actual,Unnamed: 13
0,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.09,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.12,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [ ]:
# for import only first 20 rows
# df = pd.read_csv("/content/demo.csv", nrows=20)

In [ ]:
# df

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
5,SSSQ.SFMN1111CA,2005.09,1299.487,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
6,SSSQ.SFMN1111CA,2005.12,1343.035,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
7,SSSQ.SFMN1111CA,2006.03,1299.705,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
8,SSSQ.SFMN1111CA,2006.06,1469.855,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
9,SSSQ.SFMN1111CA,2006.09,1443.402,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
10,SSSQ.SFMN1111CA,2006.12,1455.796,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
11,SSSQ.SFMN1111CA,2007.03,1413.794,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
12,SSSQ.SFMN1111CA,2007.06,1583.683,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
13,SSSQ.SFMN1111CA,2007.09,1533.197,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
14,SSSQ.SFMN1111CA,2007.12,1667.257,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
15,SSSQ.SFMN1111CA,2008.03,1543.747,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
16,SSSQ.SFMN1111CA,2008.06,1743.601,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
17,SSSQ.SFMN1111CA,2008.09,1640.113,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
18,SSSQ.SFMN1111CA,2008.12,1693.695,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
19,SSSQ.SFMN1111CA,2009.03,1548.401,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [ ]:
# for specific encoding
# df = pd.read_csv("/content/demo.csv", encoding='latin-1')

In [ ]:
# for skip rows that have extra column
# df = pd.read_csv("/content/demo.csv", on_bad_lines='skip')

In [ ]:
# df

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,SSSQ.SFRS2121CT,2023.03,NaN,NaN,C,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN
1196,SSSQ.SFRS2121CT,2023.06,NaN,NaN,C,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN
1197,SSSQ.SFRS2121CT,2023.09,NaN,NaN,C,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN
1198,SSSQ.SFRS2121CT,2023.12,NaN,NaN,C,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN
1199,SSSQ.SFRS2121CT,2024.03,NaN,NaN,C,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN

In [ ]:
# for change type of any column like here change int to float
# df = pd.read_csv("/content/demo.csv",dtype={'Magnitude': float})

In [ ]:
# df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Series_reference  1200 non-null   object
 1   Period            1200 non-null   float64
 2   Data_value        1115 non-null   float64
 3   Suppressed        0 non-null      float64
 4   STATUS            1200 non-null   object
 5   UNITS             1200 non-null   object
 6   Magnitude         1200 non-null   float64
 7   Subject           1200 non-null   object
 8   Group             1200 non-null   object
 9   Series_title_1    1200 non-null   object
 10  Series_title_2    1200 non-null   object
 11  Series_title_3    1200 non-null   object
 12  Series_title_4    1200 non-null   object
 13  Series_title_5    0 non-null      float64
dtypes: float64(5), object(9)
memory usage: 131.4+ KB

In [ ]:
# for change any column type as date
# df = pd.read_csv("/content/demo.csv", parse_dates=['Period'])
# df.info()

In [4]:
# df = pd.read_csv("/content/demo.csv")

In [5]:
# df.head(5)

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,dollars,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN

In [6]:
# create function rename which convert "dollars" in to "$"
# def rename(name):
#   if name == "dollars":
#     return "$"
#   else:
#     return name

In [7]:
# call the function rename
# rename("dollars")

'$'

In [8]:
# change column(UNITS) value "dollars" into "$" using converters and rename
# pd.read_csv("/content/demo.csv", converters={'UNITS' : rename})

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,$,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,$,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,$,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,$,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,$,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,SSSQ.SFRS2121CT,2023.03,NaN,NaN,C,$,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN
1196,SSSQ.SFRS2121CT,2023.06,NaN,NaN,C,$,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN
1197,SSSQ.SFRS2121CT,2023.09,NaN,NaN,C,$,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN
1198,SSSQ.SFRS2121CT,2023.12,NaN,NaN,C,$,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN
1199,SSSQ.SFRS2121CT,2024.03,NaN,NaN,C,$,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN

In [11]:
# convert and column value as null value(NAN) with na_values
# you can add more column value by giving comma(,) in square bracket
# pd.read_csv("/content/demo.csv", na_values=['dollars'])

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,SSSQ.SFMN1111CA,2004.06,1248.356,NaN,F,NaN,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
1,SSSQ.SFMN1111CA,2004.09,1220.571,NaN,F,NaN,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
2,SSSQ.SFMN1111CA,2004.12,1263.820,NaN,F,NaN,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
3,SSSQ.SFMN1111CA,2005.03,1146.156,NaN,F,NaN,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
4,SSSQ.SFMN1111CA,2005.06,1382.692,NaN,F,NaN,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Scientific, Architectural and Engineering Serv...",Sales (operating income),Current prices,Actual,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,SSSQ.SFRS2121CT,2023.03,NaN,NaN,C,NaN,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN
1196,SSSQ.SFRS2121CT,2023.06,NaN,NaN,C,NaN,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN
1197,SSSQ.SFRS2121CT,2023.09,NaN,NaN,C,NaN,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN
1198,SSSQ.SFRS2121CT,2023.12,NaN,NaN,C,NaN,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN
1199,SSSQ.SFRS2121CT,2024.03,NaN,NaN,C,NaN,6,Selected Services Survey (ANZSIC06) - SSS,Industry sales - Subannual Financial Collection,"Personal Care, Funeral and Other Personal Serv...",Sales (operating income),Current prices,Trend,NaN

In [13]:
# seprate dataset in to parts by chunksize
# dfs = pd.read_csv("/content/demo.csv", chunksize= 600)

In [15]:
# print chunks shape
# for chunks in dfs:
#   print(chunks.shape)

(600, 14)